<a href="https://colab.research.google.com/github/brainmentorspvtltd/IGDTU_ImageProcessingTF/blob/main/IG_ANN_FromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
X = np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]
])

y = np.array([[1],[1],[0]])

In [3]:
X.shape

(3, 4)

In [4]:
inputNeurons = X.shape[1]
hiddenNeurons = 4
outputNeurons = 1

In [5]:
weightsHidden = np.random.uniform(size=(inputNeurons, hiddenNeurons))
biasHidden = np.random.uniform(size=(1,hiddenNeurons))
weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons))
biasOutput = np.random.uniform(size=(1,outputNeurons))

In [6]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [7]:
# Feedforward

# Step - 1 - apply linear equation
fx1 = np.dot(X, weightsHidden) + biasHidden

# Step - 2 - apply activation for non-linearity
z = sigmoid(fx1)

In [8]:
fx1

array([[0.87401113, 0.34321397, 2.47949433, 0.56804463],
       [1.83575394, 0.68086545, 2.73104661, 0.94896631],
       [1.61196121, 0.8279703 , 1.28507418, 1.34762227]])

In [9]:
z

array([[0.70557964, 0.58497102, 0.92269174, 0.63831186],
       [0.86244576, 0.66393183, 0.93883397, 0.72090725],
       [0.8336835 , 0.69592559, 0.78331228, 0.79374063]])

In [10]:
# Step - 3 : apply linear equation on output of hidden layer
fx2 = np.dot(z, weightsOutput) + biasOutput

# Step - 4 : apply activation on output layer
output = sigmoid(fx2)

In [11]:
output

array([[0.86955693],
       [0.88507387],
       [0.880708  ]])

In [12]:
y

array([[1],
       [1],
       [0]])