<a href="https://colab.research.google.com/github/brainmentorspvtltd/IGDTU_ImageProcessingTF/blob/main/IG_ANN_FromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X = np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]
])

y = np.array([[1],[1],[0]])

In [ ]:
X.shape

(3, 4)

In [ ]:
inputNeurons = X.shape[1]
hiddenNeurons = 4
outputNeurons = 1
alpha = 0.1

In [ ]:
weightsHidden = np.random.uniform(size=(inputNeurons, hiddenNeurons))
biasHidden = np.random.uniform(size=(1,hiddenNeurons))
weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons))
biasOutput = np.random.uniform(size=(1,outputNeurons))

In [ ]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def derivativeSigmoid(x):
  return x * (1 - x)

In [ ]:
# Feedforward

# Step - 1 - apply linear equation
fx1 = np.dot(X, weightsHidden) + biasHidden

# Step - 2 - apply activation for non-linearity
z = sigmoid(fx1)

In [ ]:
fx1

array([[1.2756284 , 1.54262829, 1.2569226 , 1.82126204],
       [1.35570649, 1.75022543, 1.87381141, 2.64108591],
       [0.40243901, 1.06147263, 1.07452495, 1.24513202]])

In [ ]:
z

array([[0.78170472, 0.82384648, 0.77849589, 0.86071749],
       [0.795061  , 0.85198123, 0.86689867, 0.93345945],
       [0.59927352, 0.74297187, 0.74545648, 0.77645605]])

In [ ]:
# Step - 3 : apply linear equation on output of hidden layer
fx2 = np.dot(z, weightsOutput) + biasOutput

# Step - 4 : apply activation on output layer
output = sigmoid(fx2)

In [ ]:
output

array([[0.86345178],
       [0.8744019 ],
       [0.84896923]])

In [ ]:
y

array([[1],
       [1],
       [0]])

In [ ]:
outputLoss = output - y

In [ ]:
outputLoss

array([[-0.13654822],
       [-0.1255981 ],
       [ 0.84896923]])

In [ ]:
outputSlope = derivativeSigmoid(output)

In [ ]:
output

array([[0.86345178],
       [0.8744019 ],
       [0.84896923]])

In [ ]:
outputSlope

array([[0.1179028 ],
       [0.10982322],
       [0.12822047]])

In [ ]:
deltaOutput = outputLoss * outputSlope

In [ ]:
deltaOutput

array([[-0.01609942],
       [-0.01379359],
       [ 0.10885524]])

In [ ]:
hiddenLoss = np.dot(deltaOutput, weightsOutput.T)

In [ ]:
hiddenLoss

array([[-0.0003746 , -0.01507775, -0.00993641, -0.00331347],
       [-0.00032095, -0.01291825, -0.00851327, -0.0028389 ],
       [ 0.00253284,  0.10194731,  0.06718445,  0.02240384]])

In [ ]:
hiddenSlope = derivativeSigmoid(z)
hiddenDelta = hiddenLoss * hiddenSlope

In [ ]:
# Weights and Bias Optimization

In [ ]:
weightsOutput = weightsOutput - z.T.dot(deltaOutput) * alpha
weightsHidden = weightsHidden - X.T.dot(hiddenDelta) * alpha
biasOutput = biasOutput - np.sum(deltaOutput) * alpha
biasHidden = biasHidden - np.sum(hiddenDelta) * alpha

In [ ]:
epochs = 5000

weightsHidden = np.random.uniform(size=(inputNeurons, hiddenNeurons))
biasHidden = np.random.uniform(size=(1,hiddenNeurons))
weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons))
biasOutput = np.random.uniform(size=(1,outputNeurons))

for i in range(epochs):

  # Feedforward
  # Step - 1 - apply linear equation
  fx1 = np.dot(X, weightsHidden) + biasHidden
  # Step - 2 - apply activation for non-linearity
  z = sigmoid(fx1)
  # Step - 3 : apply linear equation on output of hidden layer
  fx2 = np.dot(z, weightsOutput) + biasOutput
  # Step - 4 : apply activation on output layer
  output = sigmoid(fx2)

  # Backpropagation
  outputLoss = output - y
  outputSlope = derivativeSigmoid(output)
  deltaOutput = outputLoss * outputSlope
  
  hiddenLoss = np.dot(deltaOutput, weightsOutput.T)
  hiddenSlope = derivativeSigmoid(z)
  hiddenDelta = hiddenLoss * hiddenSlope

  # Weights and Bias Optimization
  weightsOutput = weightsOutput - z.T.dot(deltaOutput) * alpha
  weightsHidden = weightsHidden - X.T.dot(hiddenDelta) * alpha
  biasOutput = biasOutput - np.sum(deltaOutput) * alpha
  biasHidden = biasHidden - np.sum(hiddenDelta) * alpha

In [ ]:
output

array([[0.9823114 ],
       [0.97627149],
       [0.0332416 ]])

In [ ]:
outputLoss

array([[-0.0176886 ],
       [-0.02372851],
       [ 0.0332416 ]])