In [1]:
# Computer Vision using Opencv
# image - collection of pixels
# we get an array when we read any image

In [3]:
!pip install opencv-python

In [1]:
import cv2

In [2]:
img = cv2.imread("img_1.jpg")

In [3]:
type(img)

numpy.ndarray

In [4]:
img.shape

(450, 600, 3)

In [5]:
# opencv reads BGR instead of RGB
img[0]

array([[251, 220, 205],
       [251, 220, 205],
       [250, 219, 204],
       ...,
       [250, 219, 204],
       [251, 220, 205],
       [251, 220, 205]], dtype=uint8)

In [6]:
cv2.imshow("result", img)
cv2.waitKey(0)

-1

In [8]:
# Preprocessing on images
# - Normalization
# - Blurring
# - GrayScale
# - Scaling
# - Noise Removal
# - Threshold

In [12]:
# 0th row
img[0]

array([[251, 220, 205],
       [251, 220, 205],
       [250, 219, 204],
       ...,
       [250, 219, 204],
       [251, 220, 205],
       [251, 220, 205]], dtype=uint8)

In [11]:
# 0th col
img[:,0]

array([[251, 220, 205],
       [251, 220, 205],
       [250, 219, 204],
       ...,
       [250, 219, 204],
       [248, 217, 202],
       [250, 219, 204]], dtype=uint8)

In [16]:
img_2 = cv2.resize(img,(224,224))

In [17]:
img_2.shape

(224, 224, 3)

In [18]:
cv2.imshow('img_1', img)
cv2.imshow('img_2', img_2)
cv2.waitKey(0)

-1

In [19]:
# GrayScale

In [20]:
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow('res',gray_img)
cv2.waitKey(0)

-1

In [23]:
# Thresholding - Binary Threshold
x, thresh_output = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

cv2.imshow('res_1', img)
cv2.imshow('res_2', thresh_output)
cv2.waitKey(0)

-1

In [25]:
# Noise Reduction - filters
# Median Filter
# Gaussian Filter

In [27]:
median = cv2.medianBlur(gray_img, 5)
cv2.imshow('res_1', gray_img)
cv2.imshow('res_2', median)
cv2.waitKey(0)

-1

In [31]:
gauss = cv2.GaussianBlur(gray_img, (7,7), 5)
cv2.imshow('res_1', gray_img)
cv2.imshow('res_2', gauss)
cv2.waitKey(0)

-1

In [32]:
# Edge Detection

In [33]:
# Canny Edge Detector
# - multi-stage algorithm
# 1. Noise Reduction - applies gaussian filter
# 2. Find intensity gradient of the image - Sobel Kernel/Filter
# 3. Non-Max Supression
# 4. Hysteresis Thresholding

In [39]:
edges = cv2.Canny(img, 100,200)

cv2.imshow('res_1', img)
cv2.imshow('res_2', edges)
cv2.waitKey(0)

-1